--- 
title: "febr -- Catálogo de Conjuntos de Dados"
# subtitle: "Catálogo de Conjuntos de Dados"
# author: "Equipe febr"
# date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
github-repo: febr-team/febr-catalog
# description: "Catálogo dos conjuntos de dados disponíveis no febr"
description: "Repositório Brasileiro Livre para Dados Abertos do Solo"
# url: http://www.ufsm.br/febr/
---

```{r, eval=FALSE}
# AFTER BUILDING THE BOOK, EDIT FILE '/docs/libs/gitbook-2.6.7/js/plugin-bookdown.js' TO MAKE SURE THAT THE
# SITE HEADING BACKGROUND COLOR IS CORRECT.
js <- list.files(path = ".", recursive = TRUE)
idx <- grepl(pattern = "/js/plugin-bookdown.js", x = js)
file <- js[idx]
js <- readLines(con = file)
for (i in seq(length(js))) {
  js[i] <- 
    gsub(
      pattern = ".css('background-color', bookBody.css('background-color'))", 
      replacement = ".css('background-color')", x = js[i], fixed = TRUE)
}
writeLines(text = js, con = file)
```

```{r, echo=FALSE}
library(knitr)
knitr::opts_chunk$set(
  dev.args = list(bg = 'transparent'), out.width = '100%', out.height = '80vh', echo = FALSE)
library(magrittr)
library(pander)
library(glue)
library(febr)
library(sp)
library(mapview)
library(readr)
library(googlesheets)
```

# Instruções de uso {-}

Conheça detalhadamente as características de cada um dos conjuntos de dados abertos do solo. Saiba como os dados foram gerados e dê os devidos créditos às pessoas e instituições responsáveis.

```{r keys}
key <- "18yP9Hpp8oMdbGsf6cVu4vkDv-Dj-j5gjEFgEXN-5H-Q"
sheets_keys <- try(gs_key(key) %>% gs_read_csv(), TRUE)
if (class(sheets_keys) == "try-error") {
  url <- glue("https://docs.google.com/spreadsheets/d/{key}/export?format=csv")
  tempfile <- tempfile(fileext = "cvs")
  download.file(url, destfile = tempfile)
  sheets_keys <- read_csv(tempfile)
}
```

```{r}
# dts <- datasets(dataset = 'all')
# obs <- observations(dataset = 'all', missing.coords = 'keep', stack.obs = FALSE)
# save(dts, file = "data/dts.rda")
# save(obs, file = "data/obs.rda")
load("data/dts.rda")
load("data/obs.rda")
```

```{r, echo=FALSE}
j <- 1:length(dts)
j <- 1:5
dts <- dts[j]
obs <- obs[j]
n <- length(dts)
id <- sapply(dts, function (x) x[1, 2] %>% as.character())
```

```{r, include=FALSE}
src <- lapply(seq(n), function (i) knit_expand(file = "template.Rmarkdown", delim = c("**", "**")))
```

`r knit(text = unlist(src))`
